apiVersion: v1
entries:
  meshery:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-04-05T08:54:19.555064068Z"
    dependencies:
    - condition: meshery-istio.enabled
      name: meshery-istio
      repository: ""
      version: 2.0.1
    - condition: meshery-linkerd.enabled
      name: meshery-linkerd
      repository: ""
      version: 2.0.1
    - condition: meshery-consul.enabled
      name: meshery-consul
      repository: ""
      version: 2.0.1
    - condition: meshery-kuma.enabled
      name: meshery-kuma
      repository: ""
      version: 1.0.1
    - condition: meshery-osm.enabled
      name: meshery-osm
      repository: ""
      version: 1.0.1
    - condition: meshery-nsm.enabled
      name: meshery-nsm
      repository: ""
      version: 1.0.1
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: 8c21e030f7fa59d2decbcd0b3a3c1cff34f5832828d8ff2ec0a933e0288c9a58
    icon: https://meshery.io/images/logos/meshery-logo.png
    keywords:
    - meshery
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-kuma
    - meshery-osm
    - meshery-nsm
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery
    type: application
    urls:
    - https://github.com/Aisuko/charts-release/releases/download/meshery-2.1.50/meshery-2.1.50.tgz
    version: 2.1.50
generated: "2021-04-05T08:54:19.555069668Z"
